-- SQL Queries for E-commerce Analytics

-- 1. Retrieve all products from the products table
SELECT * FROM products;

-- 2. Get the total sales amount for each product
SELECT product_id, SUM(sales_amount) AS total_sales
FROM sales
GROUP BY product_id;

-- 3. Find the top 10 customers by total purchase amount
SELECT customer_id, SUM(sales_amount) AS total_purchase
FROM sales
GROUP BY customer_id
ORDER BY total_purchase DESC
LIMIT 10;

-- 4. Get the average order value
SELECT AVG(order_value) AS average_order_value
FROM orders;

-- 5. Count the number of orders placed in the last month
SELECT COUNT(*) AS total_orders_last_month
FROM orders
WHERE order_date >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH);

-- 6. Retrieve the list of customers who have not made any purchases
SELECT customer_id
FROM customers
WHERE customer_id NOT IN (SELECT DISTINCT customer_id FROM sales);

-- 7. Get the sales trend over the last year
SELECT DATE_FORMAT(order_date, '%Y-%m') AS month, SUM(sales_amount) AS total_sales
FROM sales
WHERE order_date >= DATE_SUB(CURDATE(), INTERVAL 1 YEAR)
GROUP BY month
ORDER BY month;

-- 8. Find the most popular product category
SELECT category_id, COUNT(*) AS product_count
FROM products
GROUP BY category_id
ORDER BY product_count DESC
LIMIT 1;

-- 9. Get the total revenue generated by each category
SELECT category_id, SUM(sales_amount) AS total_revenue
FROM sales
JOIN products ON sales.product_id = products.product_id
GROUP BY category_id;

-- 10. Retrieve customer details along with their total spending
SELECT c.customer_id, c.customer_name, SUM(s.sales_amount) AS total_spending
FROM customers c
LEFT JOIN sales s ON c.customer_id = s.customer_id
GROUP BY c.customer_id;